version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./queries:/app/queries
    ports:
      - "5433:5432"

  app:
    build: 
      context: .
      dockerfile: Dockerfile_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: postgres_db
      DB_USER: postgres_user
      DB_PASSWORD: admin
      DB_PORT: 5432
    volumes:
      - ./logs:/app/logs
      - ./csv_files:/app/csv_files
      - ./queries:/app/queries
