
FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y postgresql-client

# CMD ["sh", "-c", "python etl.py && python execute_sql.py"]

CMD ["python", "etl.py"]



